# AutomakeReader.cmake
#
# Reads VICE's own automake inputs (the Makefile.am files) and turns them into
# CMake targets, so that source lists live in one place and this build follows
# them rather than duplicating them.
#
# The reader understands a deliberately small grammar. Anything outside it is
# a FATAL_ERROR naming the file and line, so that a construct the reader does
# not understand can never be silently skipped:
#
#   - blank lines, `#` comments, recipe lines (leading TAB): skipped
#   - backslash continuations: joined
#   - `if COND` / `if !COND` / `else` / `endif` at column 0 (trailing text on
#     `else`/`endif` ignored); COND must be in the profile's conditional table
#   - `NAME = value` and `NAME += value`, in active branches
#   - rules (a line whose first `:` precedes its first `=`, or that has no
#     `=`): skipped, together with their continuation and recipe lines
#
# Values are expanded when used: `@NAME@` from the profile's substitution
# table (an unknown name is an error), then `$(NAME)` / `${NAME}` / `$(NAME:.a=.b)`
# recursively (depth limit 32); an undefined make variable is empty.
#
# Entry points:
#   am_walk(<dir>)                       read <dir>/Makefile.am and, through
#                                        SUBDIRS, every directory below it
#   am_define_program(<name>)            define an executable from src/Makefile.am
#   am_dump(<file>)                      write the target table (VICE_AM_DUMP)

set(AM_TAB "\t")

# Placeholders that keep CMake list syntax from touching Makefile text.
set(AM_SEMI "<<AM-SEMI>>")
set(AM_LBRK "<<AM-LBRK>>")
set(AM_RBRK "<<AM-RBRK>>")
set(AM_CONT "<<AM-CONT>>")

# ---------------------------------------------------------------------------
# variable store: one global property per (directory, variable)
# ---------------------------------------------------------------------------

function(am_set dir name value)
    set_property(GLOBAL PROPERTY "AM:${dir}:${name}" "${value}")
endfunction()

function(am_is_set dir name out)
    get_property(_set GLOBAL PROPERTY "AM:${dir}:${name}" SET)
    set(${out} "${_set}" PARENT_SCOPE)
endfunction()

function(am_raw dir name out)
    get_property(_v GLOBAL PROPERTY "AM:${dir}:${name}")
    set(${out} "${_v}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# expansion
# ---------------------------------------------------------------------------

# Value of a make variable as seen from <dir>'s Makefile.am, unexpanded.
function(am_lookup dir name out)
    am_is_set("${dir}" "${name}" _set)
    if(_set)
        am_raw("${dir}" "${name}" _v)
        set(${out} "${_v}" PARENT_SCOPE)
        return()
    endif()
    if(name STREQUAL "top_srcdir")
        set(${out} "${VICE_SOURCE_DIR}" PARENT_SCOPE)
    elseif(name STREQUAL "top_builddir")
        set(${out} "${VICE_BINARY_DIR}" PARENT_SCOPE)
    elseif(name STREQUAL "srcdir")
        set(${out} "${VICE_SOURCE_DIR}/${dir}" PARENT_SCOPE)
    elseif(name STREQUAL "builddir")
        set(${out} "${VICE_BINARY_DIR}/${dir}" PARENT_SCOPE)
    elseif(name STREQUAL "PACKAGE")
        set(${out} "${VICE_PACKAGE}" PARENT_SCOPE)
    elseif(name STREQUAL "EXEEXT")
        set(${out} "" PARENT_SCOPE)
    elseif(DEFINED AMP_BUILTIN_${name})
        set(${out} "${AMP_BUILTIN_${name}}" PARENT_SCOPE)
    elseif(DEFINED AMP_SUBST_${name})
        # configure-output variables that a Makefile.am uses without assigning
        set(${out} "${AMP_SUBST_${name}}" PARENT_SCOPE)
    else()
        set(${out} "" PARENT_SCOPE)
    endif()
endfunction()

function(am_expand dir text out)
    set(_t "${text}")
    set(_round 0)
    while(TRUE)
        string(REGEX MATCHALL "@[A-Za-z0-9_]+@" _subs "${_t}")
        foreach(_s IN LISTS _subs)
            string(LENGTH "${_s}" _n)
            math(EXPR _n2 "${_n}-2")
            string(SUBSTRING "${_s}" 1 ${_n2} _name)
            if(NOT DEFINED AMP_SUBST_${_name})
                message(FATAL_ERROR
                    "${dir}/Makefile.am: unknown substitution ${_s} "
                    "(not in the ${VICE_PROFILE_NAME} profile)")
            endif()
            string(REPLACE "${_s}" "${AMP_SUBST_${_name}}" _t "${_t}")
        endforeach()

        string(REGEX MATCHALL "\\$[({][A-Za-z0-9_.@/:=-]+[)}]" _refs "${_t}")
        if(NOT _refs AND NOT _subs)
            break()
        endif()
        foreach(_r IN LISTS _refs)
            string(LENGTH "${_r}" _n)
            math(EXPR _n2 "${_n}-3")
            string(SUBSTRING "${_r}" 2 ${_n2} _inner)
            string(FIND "${_inner}" ":" _colon)
            if(_colon GREATER -1)
                # $(VAR:.a=.b)
                string(SUBSTRING "${_inner}" 0 ${_colon} _vname)
                math(EXPR _rest "${_colon}+1")
                string(SUBSTRING "${_inner}" ${_rest} -1 _pat)
                string(FIND "${_pat}" "=" _eq)
                if(_eq EQUAL -1)
                    message(FATAL_ERROR
                        "${dir}/Makefile.am: malformed substitution reference ${_r}")
                endif()
                string(SUBSTRING "${_pat}" 0 ${_eq} _from)
                math(EXPR _eq1 "${_eq}+1")
                string(SUBSTRING "${_pat}" ${_eq1} -1 _to)
                am_lookup("${dir}" "${_vname}" _val)
                am_expand("${dir}" "${_val}" _val)
                string(REPLACE "${_from} " "${_to} " _val "${_val} ")
                string(STRIP "${_val}" _val)
            else()
                am_lookup("${dir}" "${_inner}" _val)
            endif()
            string(REPLACE "${_r}" "${_val}" _t "${_t}")
        endforeach()
        math(EXPR _round "${_round}+1")
        if(_round GREATER 32)
            message(FATAL_ERROR
                "${dir}/Makefile.am: variable expansion deeper than 32 in: ${text}")
        endif()
    endwhile()
    if(_t MATCHES "\\$[({]")
        message(FATAL_ERROR
            "${dir}/Makefile.am: unexpandable make reference in: ${_t}")
    endif()
    set(${out} "${_t}" PARENT_SCOPE)
endfunction()

# Whitespace-separated words of <text> as a CMake list.
function(am_words text out)
    string(STRIP "${text}" _t)
    string(REGEX REPLACE "[ \t]+" ";" _t "${_t}")
    set(${out} "${_t}" PARENT_SCOPE)
endfunction()

# Expanded words of a variable.
function(am_var_words dir name out)
    am_lookup("${dir}" "${name}" _raw)
    am_expand("${dir}" "${_raw}" _v)
    am_words("${_v}" _w)
    set(${out} "${_w}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# reading one Makefile.am
# ---------------------------------------------------------------------------

function(am_read dir)
    set(_file "${VICE_SOURCE_DIR}/${dir}/Makefile.am")
    if(NOT EXISTS "${_file}")
        message(FATAL_ERROR "${dir}/Makefile.am: no such file")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}")

    file(READ "${_file}" _c)
    string(REPLACE "\r" "" _c "${_c}")
    string(REPLACE ";" "${AM_SEMI}" _c "${_c}")
    string(REPLACE "[" "${AM_LBRK}" _c "${_c}")
    string(REPLACE "]" "${AM_RBRK}" _c "${_c}")
    string(REPLACE "\\\n" "${AM_CONT}\n" _c "${_c}")
    string(REPLACE "\n" ";" _lines "${_c}")
    list(LENGTH _lines _n)

    set(_pending "")
    set(_pending_line 0)
    set(_stack_parent "")
    set(_stack_cond "")
    set(_active 1)

    math(EXPR _last "${_n}-1")
    foreach(_i RANGE 0 ${_last})
        list(GET _lines ${_i} _raw)
        math(EXPR _lineno "${_i}+1")

        # join backslash continuations
        string(REGEX MATCH "${AM_CONT}$" _cont "${_raw}")
        if(_cont)
            string(LENGTH "${_raw}" _len)
            string(LENGTH "${AM_CONT}" _clen)
            math(EXPR _keep "${_len}-${_clen}")
            string(SUBSTRING "${_raw}" 0 ${_keep} _piece)
        else()
            set(_piece "${_raw}")
        endif()
        if(_pending_line)
            string(REGEX REPLACE "^[ \t]+" "" _piece "${_piece}")
            set(_pending "${_pending} ${_piece}")
            if(_cont)
                continue()
            endif()
            set(_logical "${_pending}")
            set(_start ${_pending_line})
            set(_pending "")
            set(_pending_line 0)
        else()
            if(_cont)
                set(_pending "${_piece}")
                set(_pending_line ${_lineno})
                continue()
            endif()
            set(_logical "${_piece}")
            set(_start ${_lineno})
        endif()

        # classify
        string(STRIP "${_logical}" _stripped)
        if(_stripped STREQUAL "")
            continue()
        endif()
        string(SUBSTRING "${_logical}" 0 1 _c0)
        if(_c0 STREQUAL "#" OR _c0 STREQUAL "${AM_TAB}")
            continue()
        endif()

        if(_logical MATCHES "^if[ \t]+(!?)([A-Za-z0-9_]+)[ \t]*$")
            set(_neg "${CMAKE_MATCH_1}")
            set(_cname "${CMAKE_MATCH_2}")
            if(NOT DEFINED AMP_COND_${_cname})
                message(FATAL_ERROR
                    "${dir}/Makefile.am:${_start}: unknown conditional ${_cname} "
                    "(not in the ${VICE_PROFILE_NAME} profile)")
            endif()
            set(_val ${AMP_COND_${_cname}})
            if(_neg STREQUAL "!")
                if(_val)
                    set(_val 0)
                else()
                    set(_val 1)
                endif()
            elseif(_val)
                set(_val 1)
            else()
                set(_val 0)
            endif()
            list(APPEND _stack_parent ${_active})
            list(APPEND _stack_cond ${_val})
            if(_active AND _val)
                set(_active 1)
            else()
                set(_active 0)
            endif()
            continue()
        endif()
        if(_logical MATCHES "^else([ \t].*)?$")
            list(LENGTH _stack_cond _depth)
            if(_depth EQUAL 0)
                message(FATAL_ERROR "${dir}/Makefile.am:${_start}: `else` without `if`")
            endif()
            list(GET _stack_parent -1 _p)
            list(GET _stack_cond -1 _cv)
            if(_cv)
                set(_cv 0)
            else()
                set(_cv 1)
            endif()
            list(POP_BACK _stack_cond)
            list(APPEND _stack_cond ${_cv})
            if(_p AND _cv)
                set(_active 1)
            else()
                set(_active 0)
            endif()
            continue()
        endif()
        if(_logical MATCHES "^endif([ \t].*)?$")
            list(LENGTH _stack_cond _depth)
            if(_depth EQUAL 0)
                message(FATAL_ERROR "${dir}/Makefile.am:${_start}: `endif` without `if`")
            endif()
            list(GET _stack_parent -1 _p)
            list(POP_BACK _stack_parent)
            list(POP_BACK _stack_cond)
            set(_active ${_p})
            continue()
        endif()
        if(_logical MATCHES "^[ \t]*(if|else|endif)([ \t]|$)")
            message(FATAL_ERROR
                "${dir}/Makefile.am:${_start}: conditional keyword not at column 0: ${_logical}")
        endif()

        # rule or assignment
        string(FIND "${_logical}" ":" _pc)
        string(FIND "${_logical}" "=" _pe)
        if(_pc GREATER -1 AND (_pe EQUAL -1 OR _pc LESS _pe))
            continue()
        endif()
        if(_pe EQUAL -1)
            message(FATAL_ERROR
                "${dir}/Makefile.am:${_start}: unrecognized line: ${_logical}")
        endif()
        if(NOT _logical MATCHES "^[ \t]*([A-Za-z_][A-Za-z0-9_.@-]*)[ \t]*(\\+?)=[ \t]*(.*)$")
            message(FATAL_ERROR
                "${dir}/Makefile.am:${_start}: unrecognized assignment: ${_logical}")
        endif()
        set(_name "${CMAKE_MATCH_1}")
        set(_op "${CMAKE_MATCH_2}")
        set(_value "${CMAKE_MATCH_3}")
        string(STRIP "${_value}" _value)
        if(_value MATCHES "${AM_SEMI}|${AM_LBRK}|${AM_RBRK}")
            message(FATAL_ERROR
                "${dir}/Makefile.am:${_start}: `;`, `[` or `]` in the value of ${_name}")
        endif()
        if(NOT _active)
            continue()
        endif()
        if(_op STREQUAL "+")
            am_is_set("${dir}" "${_name}" _was)
            if(_was)
                am_raw("${dir}" "${_name}" _old)
                if(_old STREQUAL "")
                    set(_value "${_value}")
                elseif(_value STREQUAL "")
                    set(_value "${_old}")
                else()
                    set(_value "${_old} ${_value}")
                endif()
            endif()
        endif()
        am_set("${dir}" "${_name}" "${_value}")
    endforeach()

    if(_pending_line)
        message(FATAL_ERROR "${dir}/Makefile.am:${_pending_line}: continuation at end of file")
    endif()
    list(LENGTH _stack_cond _depth)
    if(NOT _depth EQUAL 0)
        message(FATAL_ERROR "${dir}/Makefile.am: `if` without `endif`")
    endif()
endfunction()

# Read <dir> and every directory reachable through SUBDIRS.
function(am_walk dir)
    get_property(_seen GLOBAL PROPERTY AM_DIRS)
    if("${dir}" IN_LIST _seen)
        return()
    endif()
    set_property(GLOBAL APPEND PROPERTY AM_DIRS "${dir}")
    am_read("${dir}")
    am_var_words("${dir}" SUBDIRS _subs)
    foreach(_s IN LISTS _subs)
        am_walk("${dir}/${_s}")
    endforeach()
endfunction()

# ---------------------------------------------------------------------------
# targets
# ---------------------------------------------------------------------------

# Canonical automake name: every character that is not alphanumeric or `@`
# becomes `_`.
function(am_canon name out)
    string(REGEX REPLACE "[^A-Za-z0-9@]" "_" _c "${name}")
    set(${out} "${_c}" PARENT_SCOPE)
endfunction()

# Words of the form -I<path> / -D<macro> / other, split for a compile.
# GCC-only warning, optimisation and codegen words are dropped by pattern;
# any other word is an error.
function(am_split_flags dir words inc_out def_out)
    set(_inc "")
    set(_def "")
    foreach(_w IN LISTS words)
        if(_w MATCHES "^-I(.+)$")
            list(APPEND _inc "${CMAKE_MATCH_1}")
        elseif(_w MATCHES "^-D(.+)$")
            set(_d "${CMAKE_MATCH_1}")
            # strip one layer of shell quoting: -DNAME='"value"' -> NAME="value"
            if(_d MATCHES "^([A-Za-z0-9_]+=)'(.*)'$")
                set(_d "${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
            endif()
            list(APPEND _def "${_d}")
        elseif(_w MATCHES "^-(W.*|pedantic|g|O.*|fopenmp|m.*|std=.*)$")
            # GCC-specific: the compiler flags come from the preset
        else()
            message(FATAL_ERROR "${dir}/Makefile.am: unhandled compiler flag ${_w}")
        endif()
    endforeach()
    set(${inc_out} "${_inc}" PARENT_SCOPE)
    set(${def_out} "${_def}" PARENT_SCOPE)
endfunction()

# Compile settings of a directory (its AM_CPPFLAGS, AM_CFLAGS, AM_CXXFLAGS)
# plus automake's implicit -I<builddir> -I<srcdir> -I<top_builddir>/src.
function(am_dir_flags dir inc_out def_out)
    set(_words "")
    foreach(_v AM_CPPFLAGS AM_CFLAGS AM_CXXFLAGS)
        am_var_words("${dir}" ${_v} _w)
        list(APPEND _words ${_w})
    endforeach()
    am_split_flags("${dir}" "${_words}" _inc _def)
    # macros that a directory's own configure would pass (see the profile)
    string(REPLACE "/" "_" _key "${dir}")
    if(DEFINED AMP_DIR_DEFINES_${_key})
        list(APPEND _def ${AMP_DIR_DEFINES_${_key}})
    endif()
    set(_all "${VICE_BINARY_DIR}/${dir}" "${VICE_SOURCE_DIR}/${dir}" "${VICE_BINARY_DIR}/src")
    list(APPEND _all ${_inc})
    list(REMOVE_DUPLICATES _all)
    list(REMOVE_DUPLICATES _def)
    set(${inc_out} "${_all}" PARENT_SCOPE)
    set(${def_out} "${_def}" PARENT_SCOPE)
endfunction()

# Resolve a `.o` entry of _LIBADD/_DEPENDENCIES to its source file name.
function(am_object_source dir canon obj out)
    string(REGEX REPLACE "\\.o$" "" _base "${obj}")
    am_var_words("${dir}" EXTRA_${canon}_SOURCES _extra)
    foreach(_e IN LISTS _extra)
        if(_e MATCHES "^${_base}\\.(c|cc|cpp)$")
            set(${out} "${_e}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    foreach(_ext c cc cpp)
        if(EXISTS "${VICE_SOURCE_DIR}/${dir}/${_base}.${_ext}")
            set(${out} "${_base}.${_ext}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR
        "${dir}/Makefile.am: ${obj} (of ${canon}) matches no source file")
endfunction()

# Source files of a library or program: its _SOURCES, the sources behind the
# .o entries of _LIBADD/_DEPENDENCIES, minus the .c files that the directory
# lists in noinst_HEADERS/EXTRA_DIST (fragments that other files #include).
# `.y`/`.l` inputs are replaced by their generated .c and recorded.
function(am_sources dir canon out)
    am_var_words("${dir}" ${canon}_SOURCES _src)
    foreach(_v LIBADD DEPENDENCIES)
        am_var_words("${dir}" ${canon}_${_v} _objs)
        foreach(_o IN LISTS _objs)
            if(_o MATCHES "\\.o$")
                am_object_source("${dir}" "${canon}" "${_o}" _s)
                list(APPEND _src "${_s}")
            endif()
        endforeach()
    endforeach()

    am_var_words("${dir}" noinst_HEADERS _hdr)
    am_var_words("${dir}" EXTRA_DIST _extra)
    set(_frag ${_hdr} ${_extra})

    set(_result "")
    foreach(_s IN LISTS _src)
        if(_s MATCHES "\\.(h|a65|m)$")
            continue()
        endif()
        if(_s MATCHES "^(.*)\\.y$")
            set(_g "${CMAKE_MATCH_1}")
            set_property(GLOBAL APPEND PROPERTY AM_YACC "${dir}|${_g}")
            list(APPEND _result "${VICE_BINARY_DIR}/${dir}/${_g}.c")
            continue()
        endif()
        if(_s MATCHES "^(.*)\\.l$")
            set(_g "${CMAKE_MATCH_1}")
            set_property(GLOBAL APPEND PROPERTY AM_LEX "${dir}|${_g}")
            list(APPEND _result "${VICE_BINARY_DIR}/${dir}/${_g}.c")
            continue()
        endif()
        if(NOT _s MATCHES "\\.(c|cc|cpp)$")
            message(FATAL_ERROR "${dir}/Makefile.am: unhandled source kind ${_s}")
        endif()
        if(_s IN_LIST _frag AND NOT AM_NO_FRAGMENT_EXCLUSION)
            continue()
        endif()
        if(NOT EXISTS "${VICE_SOURCE_DIR}/${dir}/${_s}")
            message(FATAL_ERROR "${dir}/Makefile.am: ${_s} does not exist")
        endif()
        list(APPEND _result "${VICE_SOURCE_DIR}/${dir}/${_s}")
    endforeach()
    list(REMOVE_DUPLICATES _result)
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

# Define the static library for <dir>/<libfile>; returns its target name.
# A library is defined the first time something links it.
function(am_need_archive path out)
    # path: <top_builddir>/<dir>/lib<x>.a
    string(REPLACE "${VICE_BINARY_DIR}/" "" _rel "${path}")
    if(_rel STREQUAL "${path}")
        message(FATAL_ERROR "archive outside the build tree: ${path}")
    endif()
    get_filename_component(_dir "${_rel}" DIRECTORY)
    get_filename_component(_file "${_rel}" NAME)

    get_property(_done GLOBAL PROPERTY "AM_LIB:${_rel}")
    if(_done)
        set(${out} "${_done}" PARENT_SCOPE)
        return()
    endif()

    get_property(_dirs GLOBAL PROPERTY AM_DIRS)
    if(NOT "${_dir}" IN_LIST _dirs)
        message(FATAL_ERROR "${_rel}: ${_dir} is not a directory reached through SUBDIRS")
    endif()
    am_var_words("${_dir}" noinst_LIBRARIES _libs)
    if(NOT "${_file}" IN_LIST _libs)
        message(FATAL_ERROR "${_dir}/Makefile.am: ${_file} is not in noinst_LIBRARIES")
    endif()

    string(REGEX REPLACE "^lib(.*)\\.a$" "\\1" _base "${_file}")
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _base "${_base}")
    set(_target "vice_${_base}")
    get_property(_taken GLOBAL PROPERTY "AM_TARGET:${_target}")
    if(_taken)
        message(FATAL_ERROR "target name ${_target} is used by both ${_taken} and ${_rel}")
    endif()
    set_property(GLOBAL PROPERTY "AM_TARGET:${_target}" "${_rel}")
    set_property(GLOBAL PROPERTY "AM_LIB:${_rel}" "${_target}")

    am_canon("${_file}" _canon)
    foreach(_suffix CPPFLAGS CFLAGS CXXFLAGS)
        am_is_set("${_dir}" "${_canon}_${_suffix}" _has)
        if(_has)
            message(FATAL_ERROR
                "${_dir}/Makefile.am: per-library ${_canon}_${_suffix} is not supported")
        endif()
    endforeach()

    am_sources("${_dir}" "${_canon}" _srcs)
    if(NOT _srcs)
        message(FATAL_ERROR "${_dir}/Makefile.am: ${_file} has no sources")
    endif()
    am_dir_flags("${_dir}" _inc _def)

    add_library(${_target} STATIC ${_srcs})
    target_include_directories(${_target} PRIVATE ${_inc})
    if(_def)
        target_compile_definitions(${_target} PRIVATE ${_def})
    endif()
    vice_configure_target(${_target})
    set_property(GLOBAL APPEND PROPERTY AM_TARGETS "${_target}")
    set_property(GLOBAL PROPERTY "AM_INFO:${_target}" "static|${_dir}|${_srcs}")
    set_property(GLOBAL PROPERTY "AM_INC:${_target}" "${_inc}")
    set_property(GLOBAL PROPERTY "AM_DEF:${_target}" "${_def}")
    set(${out} "${_target}" PARENT_SCOPE)
endfunction()

# Define an executable of src/Makefile.am. Its archives are the .a paths in
# <name>_LDADD; `-l` words go through the profile's library map.
function(am_define_program name)
    set(_dir "src")
    am_canon("${name}" _canon)
    am_sources("${_dir}" "${_canon}" _srcs)
    if(NOT _srcs)
        message(FATAL_ERROR "${_dir}/Makefile.am: ${name} has no sources")
    endif()
    am_dir_flags("${_dir}" _inc _def)

    add_executable(${name} ${_srcs})
    target_include_directories(${name} PRIVATE ${_inc})
    if(_def)
        target_compile_definitions(${name} PRIVATE ${_def})
    endif()
    vice_configure_target(${name})

    am_var_words("${_dir}" ${_canon}_LDADD _ldadd)
    set(_link "")
    foreach(_w IN LISTS _ldadd)
        if(_w MATCHES "\\.a$")
            am_need_archive("${_w}" _t)
            list(APPEND _link "${_t}")
        elseif(_w MATCHES "^-l(.+)$")
            set(_lib "${CMAKE_MATCH_1}")
            if(NOT DEFINED AMP_LIBRARY_MAP_${_lib})
                message(FATAL_ERROR
                    "${_dir}/Makefile.am: ${name}: library -l${_lib} is not in the profile's library map")
            endif()
            list(APPEND _link "${AMP_LIBRARY_MAP_${_lib}}")
        else()
            message(FATAL_ERROR "${_dir}/Makefile.am: ${name}: unhandled link word ${_w}")
        endif()
    endforeach()
    list(APPEND _link ${AMP_PLATFORM_LIBRARIES})
    list(REMOVE_DUPLICATES _link)
    target_link_libraries(${name} PRIVATE ${_link})
    set_target_properties(${name} PROPERTIES LINKER_LANGUAGE CXX)

    set_property(GLOBAL APPEND PROPERTY AM_TARGETS "${name}")
    set_property(GLOBAL PROPERTY "AM_INFO:${name}" "program|${_dir}|${_srcs}")
    set_property(GLOBAL PROPERTY "AM_INC:${name}" "${_inc}")
    set_property(GLOBAL PROPERTY "AM_DEF:${name}" "${_def}")
    set_property(GLOBAL PROPERTY "AM_LINK:${name}" "${_link}")
endfunction()

# One block per target: name, kind, directory, sources, include directories,
# defines and (for programs) linked targets.
function(am_dump file)
    get_property(_targets GLOBAL PROPERTY AM_TARGETS)
    set(_out "")
    foreach(_t IN LISTS _targets)
        get_property(_info GLOBAL PROPERTY "AM_INFO:${_t}")
        string(REPLACE "|" ";" _parts "${_info}")
        list(GET _parts 0 _kind)
        list(GET _parts 1 _dir)
        list(REMOVE_AT _parts 0 1)
        string(APPEND _out "target ${_t}\n  kind ${_kind}\n  dir ${_dir}\n")
        foreach(_s IN LISTS _parts)
            string(APPEND _out "  source ${_s}\n")
        endforeach()
        get_property(_inc GLOBAL PROPERTY "AM_INC:${_t}")
        foreach(_i IN LISTS _inc)
            string(APPEND _out "  include ${_i}\n")
        endforeach()
        get_property(_def GLOBAL PROPERTY "AM_DEF:${_t}")
        foreach(_d IN LISTS _def)
            string(APPEND _out "  define ${_d}\n")
        endforeach()
        get_property(_link GLOBAL PROPERTY "AM_LINK:${_t}")
        foreach(_l IN LISTS _link)
            string(APPEND _out "  link ${_l}\n")
        endforeach()
        string(APPEND _out "\n")
    endforeach()
    file(WRITE "${file}" "${_out}")
endfunction()
